# -*- coding: utf-8 -*-
"""Hello World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HILjIJsi8wkyzgWngHKmnG7hYJHBG6P4
"""

my_name = "World"
print("Hello " + my_name + "!")